"""add chat_id

Revision ID: b52a34a45030
Revises: 6e48e3e683b4
Create Date: 2025-03-12 15:43:38.898119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52a34a45030'
down_revision = '6e48e3e683b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_chat_id', sa.String(), nullable=True))
    op.create_unique_constraint('uix_currentchatid', 'users', ['current_chat_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_currentchatid', 'users', type_='unique')
    op.drop_column('users', 'current_chat_id')
    # ### end Alembic commands ###
