"""add chat_ref_id

Revision ID: ee3c4da93830
Revises: b52a34a45030
Create Date: 2025-03-13 17:32:27.716328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3c4da93830'
down_revision = 'b52a34a45030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_chat_ref_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_chat_ref_id')
    # ### end Alembic commands ###
